version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: chore(github)
    cooldown:
      default-days: 3
    groups:
      all-non-major:
        patterns: ["*"]
        update-types: [minor, patch]
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: chore
    cooldown:
      default-days: 3
    groups:
      all-non-major:
        patterns: ["*"]
        update-types: [minor, patch]
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
